# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from PyQt5 import QtCore, QtGui, QtWidgets
from aqt import mw

from .api_eng import create_cards as cr


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 302)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.box_language = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.box_language.setObjectName("box_language")
        self.box_language.addItem("")
        self.box_language.addItem("")
        self.verticalLayout.addWidget(self.box_language)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 481, 131))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(30, 15, 30, 5)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_create = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_create.setObjectName("text_create")
        self.horizontalLayout.addWidget(self.text_create)
        self.text_def = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_def.setObjectName("text_def")
        self.horizontalLayout.addWidget(self.text_def)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 210, 239, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_meaning = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_meaning.setObjectName("button_meaning")
        self.horizontalLayout_2.addWidget(self.button_meaning)
        self.button_phrasals = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_phrasals.setObjectName("button_phrasals")
        self.horizontalLayout_2.addWidget(self.button_phrasals)
        self.button_multiple = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_multiple.setObjectName("button_")
        self.horizontalLayout_2.addWidget(self.button_multiple)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(269, 210, 221, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(60, 0, 60, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_definition = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_definition.setObjectName("button_definition")
        self.horizontalLayout_3.addWidget(self.button_definition)
        self.label_def = QtWidgets.QLabel(Form)
        self.label_def.setGeometry(QtCore.QRect(330, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_def.setFont(font)
        self.label_def.setObjectName("label_def")
        self.label_create = QtWidgets.QLabel(Form)
        self.label_create.setGeometry(QtCore.QRect(70, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_create.setFont(font)
        self.label_create.setObjectName("label_create")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 190, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.button_meaning.clicked.connect(lambda: self.on_click('all'))
        self.button_phrasals.clicked.connect(lambda: self.on_click('phrasal'))
        self.button_multiple.clicked.connect(lambda: self.on_click('abcd'))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_language.setItemText(0, _translate("Form", "english"))
        self.box_language.setItemText(1, _translate("Form", "german"))
        self.button_meaning.setText(_translate("Form", "all meanings"))
        self.button_phrasals.setText(_translate("Form", "phrasals"))
        self.button_multiple.setText(_translate("Form", "..."))
        self.button_definition.setText(_translate("Form", "get definition"))
        self.label_def.setText(_translate("Form", "word definition"))
        self.label_create.setText(_translate("Form", "create cards"))
        self.label.setText(_translate("Form", "you can add..."))

    def on_click(self, type):
        self.label.setText("wait, cards are being created")

        file = "file.TXT"
        path = os.path.dirname(os.path.realpath(__file__))
        path = path + "\\" + file

        self.create_cards(self.text_create.toPlainText(), path, type)


        # select deck
        did = mw.col.decks.id("test")
        mw.col.decks.select(did)

        # anki defaults to the last note type used in the selected deck
        m = mw.col.models.byName("word formation")
        deck = mw.col.decks.get(did)
        deck['mid'] = m['id']
        mw.col.decks.save(deck)

        # and puts cards in the last deck used by the note type
        m['did'] = did
        mw.col.models.save(m)
        self.label.setText("done!")

    def create_cards(self, list_words, path, type):
        app_id = 'a25b2974'
        app_key = 'fa3026e50dddff867874b8293f84b703'
        endpoint = "entries"
        language_code = "en-us"

        create = cr.CreateCards(app_id, app_key, endpoint, language_code)
        if type == 'all':
            create.multiple_cards(self.list_of_words(list_words), path)
        elif type == 'phrasal':
            create.create_phrasals(self.list_of_words(list_words), path)
        elif type == 'abcd':
            create.create_abcd(list_words, path)

        #self.textEdit_2.insertPlainText(self.textEdit.toPlainText())

    @staticmethod
    def list_of_words(text):
        list_words = text.splitlines()
        return [x.strip().split() for x in list_words]

